#1.เครื่องหมายคำนวน
#(+,-,*,/,%mod,// floor,** eponential)
print(10+3)
print(10-3)
print(10*3)
print(10/3)
print(10%3)
print(10//3)
print(10**3)
print("+++++++++++++++++++")
#เครื่องหมายค่าเปรียบเทียบ(==,!=,>,<,>=,<=)
print(10==3)
print(10!=3)
print("Bangna">="Bangpoo")
print("Thailand"<"THAILAND")
print(10>3)
print(10<=3)
print("++++++++++++++++++++++")
#เครื่องหมาย ตรรกะ(AND,OR,NOT)
print(not False)
print(not True)
print("-------")
print(True and False)
print(True and True)
print(False and False)
print(False and True)
print("-------")
print(True or False)
print(True or True)
print(False or False)
print(False or True)